### ISSUE TITLE
Cannot run on RPi4

### ISSUE THREAD

**Issue by psamim** [crazy-max/docker-nextcloud#61]
### Behaviour
Fail to run docker image on RPi 4 and HyperiotOS.

#### Steps to reproduce this issue

1. Run
```sh
docker run -d -p 8000:8000 --name nextcloud  -v "$(pwd)/nextcloud-data:/data"  crazymax/nextcloud:latest
```

#### Expected behaviour

It should run.

#### Actual behaviour

Exits, docker logs show:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-svscan: warning: unable to iopause: Invalid argument
s6-svscan: warning: executing into .s6-svscan/crash
[s6-init] ensuring user provided files have correct perms...s6-svscan panicked! Dropping to a root shell.

/bin/sh: can't access tty; job control turned off
/run/s6/services # 
```

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.12, build 48a6621
* Platform (Debian 9, Ubuntu 18.04, ...) : HyprioOS
* System info (type `uname -a`) : Linux black-pearl 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 11
  Paused: 0
  Stopped: 26
 Images: 77
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.118-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.863GiB
 Name: black-pearl
 ID: YXJF:M53F:3I5O:VSF7:2K3E:ZUZS:5MFB:FZLX:2BYB:EF3X:SCZP:ESVV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: psamim
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

### Logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-svscan: warning: unable to iopause: Invalid argument
s6-svscan: warning: executing into .s6-svscan/crash
[s6-init] ensuring user provided files have correct perms...s6-svscan panicked! Dropping to a root shell.

/bin/sh: can't access tty; job control turned off
/run/s6/services #
```

**Comment by psamim** [comment]
Error seems like https://github.com/librenms/docker/issues/188
Thought maybe it helps.

**Comment by crazy-max** [comment]
@psamim Thanks for your feedback. Should be fixed now.

**Comment by psamim** [comment]
@crazy-max Thanks! but unfortunately I am still having the same issue, should I wait for a build to complete?

**Comment by crazy-max** [comment]
@psamim You pulled the latest image right? `docker pull crazymax/nextcloud:latest`.

**Comment by psamim** [comment]
@crazy-max Yes I did pull the latest image, I still get:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...s6-svscan: warning: unable to iopause: Invalid argument
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan panicked! Dropping to a root shell.

/bin/sh: can't access tty; job control turned off
/run/s6/services # 
```

Running `docker run --rm -ti alpine:3.13 ping github.com`:

```
Unable to find image 'alpine:3.13' locally
3.13: Pulling from library/alpine
e160e00eb35d: Already exists
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine:3.13
PING github.com (140.82.121.3): 56 data bytes
64 bytes from 140.82.121.3: seq=0 ttl=45 time=109.584 ms
64 bytes from 140.82.121.3: seq=1 ttl=45 time=110.786 ms
64 bytes from 140.82.121.3: seq=2 ttl=45 time=107.497 ms
64 bytes from 140.82.121.3: seq=3 ttl=45 time=107.507 ms
64 bytes from 140.82.121.3: seq=4 ttl=45 time=107.340 ms
^C
--- github.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 107.340/108.542/110.786 ms
```

Running  `docker run --rm -ti alpine:3.12 ping github.com`:

```
Unable to find image 'alpine:3.12' locally
3.12: Pulling from library/alpine
420c7481a3a7: Pull complete
Digest: sha256:36553b10a4947067b9fbb7d532951066293a68eae893beba1d9235f7d11a20ad
Status: Downloaded newer image for alpine:3.12
PING github.com (140.82.121.3): 56 data bytes
64 bytes from 140.82.121.3: seq=0 ttl=45 time=110.206 ms
64 bytes from 140.82.121.3: seq=1 ttl=45 time=108.421 ms
64 bytes from 140.82.121.3: seq=2 ttl=45 time=107.945 ms
64 bytes from 140.82.121.3: seq=3 ttl=45 time=110.660 ms
64 bytes from 140.82.121.3: seq=4 ttl=45 time=109.285 ms
^C
--- github.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 107.945/109.303/110.660 ms
```

Running `dpkg --list | grep libseccomp`:

```
ii  libseccomp2:armhf              2.4.4-1~bpo10+1                     armhf        high level interface to Linux seccomp filter
```
